### PR TITLE
Updates to the environment/LOS section of sl.tex

### PR DESCRIPTION
**Pull request by cmccully**
Hi @drphilmarshall,
Here is a first draft of some updates to lens environment and line of sight section.

@evlinder I have added a few sentences about the spectroscopic follow-up capabilities of DESI. Is there anything you would like to add?

Thanks,
Curtis

### CODE REVIEW

**Comment by drphilmarshall** [comment]
Thanks @cmccully!

@janewman-pitt-edu Is this specific/quantitative enough for our present purposes?

**Comment by drphilmarshall** [comment]
PS. The ["Files changed"](https://github.com/wadawson/Enabling-LSST-Dark-Energy-Science/pull/5/files) link is the one to look at to see quickly what Curtis has added.

**Comment by evlinder** [comment]
Hi Curtis, 

It took me a while to dig up my notes on DESI, and make sure it was ok to spread more widely. Use whatever parts you find worthwhile. 

Spectroscopy for strong lensing time delay systems. 

There are two aspects to the use: one is getting redshifts of the lens galaxy and quasar/AGN images, plus lens galaxy velocity dispersions, and the second is getting redshifts of many galaxies along the line of sight. The first part is trivial for DESI and doesn’t require any special strategy - we want ~400-4000 redshifts, of galaxies at z<0.5 mostly and images brighter than 22 mag mostly. The second part is trickier for targeting because of fiber collisions. We want the galaxies with ~2’ of the line of sight in order to get a good estimate of the line of sight convergence, which scales the time delay distance (and Hubble constant). People are still working on exactly what information on the galaxies is best for estimating the convergence (e.g. colors, number density, etc.), but redshift is a useful datum to have. This data requires a ~4’ field, which pushes the envelope of current IFU type spectroscopy. So DESI may have a special role to play in this. Another possibility is to choose lenses along “golden” lines of sight with few galaxies, allowing the convergence uncertainty to be better determined. 

Best, 
Eric

**Comment by drphilmarshall** [comment]
Oh, good point about the fiber collisions, that could potentially be an issue for DESI.  There could be some overlap here between the facilities needed for cluster member surveying (to improve the mass function) and strong lens environments. Could you add a note on this please @cmccully ? Thanks @evlinder !

**Comment by cmccully** [comment]
I have updated the text to include some the discussion from @evlinder. @drphilmarshall or @evlinder is there anything else you would like me to add?

**Comment by drphilmarshall** [comment]
Looks good to me, Curtis! Thanks very much for your help with this.

**Pull request merged**
